"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
import pydantic
from typing import Final, TypedDict
from typing_extensions import Annotated


class ChatCompletionSentinelEventTypedDict(TypedDict):
    pass
    

class ChatCompletionSentinelEvent(BaseModel):
    DATA: Annotated[Final[str], pydantic.Field(alias="data")] = "[DONE]"
    
