"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel, Nullable
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class ChatCompletionResponseJSONModeRole(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"


class ChatCompletionResponseJSONModeMessageTypedDict(TypedDict):
    role: NotRequired[ChatCompletionResponseJSONModeRole]
    content: NotRequired[str]
    

class ChatCompletionResponseJSONModeMessage(BaseModel):
    role: Optional[ChatCompletionResponseJSONModeRole] = None
    content: Optional[str] = None
    

class ChatCompletionResponseJSONModeFinishReason(str, Enum):
    STOP = "stop"
    LENGTH = "length"
    MODEL_LENGTH = "model_length"
    ERROR = "error"
    TOOL_CALLS = "tool_calls"


class ChatCompletionResponseJSONModeChoicesTypedDict(TypedDict):
    index: int
    finish_reason: Nullable[ChatCompletionResponseJSONModeFinishReason]
    message: NotRequired[ChatCompletionResponseJSONModeMessageTypedDict]
    

class ChatCompletionResponseJSONModeChoices(BaseModel):
    index: int
    finish_reason: Nullable[ChatCompletionResponseJSONModeFinishReason]
    message: Optional[ChatCompletionResponseJSONModeMessage] = None
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["message"]
        nullable_fields = ["finish_reason"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None:
                m[k] = val
            elif not k in optional_fields or (
                    k in optional_fields
                    and k in nullable_fields
                    and (self.__pydantic_fields_set__.intersection({n}) or k in null_default_fields) # pylint: disable=no-member
                ):
                m[k] = val

        return m
        

class ChatCompletionResponseJSONModeUsageTypedDict(TypedDict):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    

class ChatCompletionResponseJSONModeUsage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    

class ChatCompletionResponseJSONModeTypedDict(TypedDict):
    id: NotRequired[str]
    object: NotRequired[str]
    created: NotRequired[int]
    model: NotRequired[str]
    choices: NotRequired[List[ChatCompletionResponseJSONModeChoicesTypedDict]]
    usage: NotRequired[ChatCompletionResponseJSONModeUsageTypedDict]
    

class ChatCompletionResponseJSONMode(BaseModel):
    id: Optional[str] = None
    object: Optional[str] = None
    created: Optional[int] = None
    model: Optional[str] = None
    choices: Optional[List[ChatCompletionResponseJSONModeChoices]] = None
    usage: Optional[ChatCompletionResponseJSONModeUsage] = None
    
