"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionchoices import ChatCompletionChoices, ChatCompletionChoicesTypedDict
from beezy_ai.types import BaseModel
from typing import TypedDict


class ChatCompletionChoicesEventTypedDict(TypedDict):
    data: ChatCompletionChoicesTypedDict
    

class ChatCompletionChoicesEvent(BaseModel):
    data: ChatCompletionChoices
    
