"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel, Nullable
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class Role(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"


class MessageTypedDict(TypedDict):
    role: NotRequired[Role]
    content: NotRequired[str]
    

class Message(BaseModel):
    role: Optional[Role] = None
    content: Optional[str] = None
    

class ChatCompletionResponseFinishReason(str, Enum):
    STOP = "stop"
    LENGTH = "length"
    MODEL_LENGTH = "model_length"
    ERROR = "error"
    TOOL_CALLS = "tool_calls"


class ChoicesTypedDict(TypedDict):
    index: int
    finish_reason: Nullable[ChatCompletionResponseFinishReason]
    message: NotRequired[MessageTypedDict]
    

class Choices(BaseModel):
    index: int
    finish_reason: Nullable[ChatCompletionResponseFinishReason]
    message: Optional[Message] = None
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["message"]
        nullable_fields = ["finish_reason"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None:
                m[k] = val
            elif not k in optional_fields or (
                    k in optional_fields
                    and k in nullable_fields
                    and (self.__pydantic_fields_set__.intersection({n}) or k in null_default_fields) # pylint: disable=no-member
                ):
                m[k] = val

        return m
        

class UsageTypedDict(TypedDict):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    

class Usage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    

class ChatCompletionResponseTypedDict(TypedDict):
    id: NotRequired[str]
    object: NotRequired[str]
    created: NotRequired[int]
    model: NotRequired[str]
    choices: NotRequired[List[ChoicesTypedDict]]
    usage: NotRequired[UsageTypedDict]
    

class ChatCompletionResponse(BaseModel):
    id: Optional[str] = None
    object: Optional[str] = None
    created: Optional[int] = None
    model: Optional[str] = None
    choices: Optional[List[Choices]] = None
    usage: Optional[Usage] = None
    
