"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionrequest import ChatCompletionRequest, ChatCompletionRequestTypedDict
from .chatcompletionrequestjsonmode import ChatCompletionRequestJSONMode, ChatCompletionRequestJSONModeTypedDict
from .chatcompletionresponse import ChatCompletionResponse, ChatCompletionResponseTypedDict
from .chatcompletionresponsefunctioncall import ChatCompletionResponseFunctionCall, ChatCompletionResponseFunctionCallTypedDict
from .chatcompletionresponsejsonmode import ChatCompletionResponseJSONMode, ChatCompletionResponseJSONModeTypedDict
from .chatfunctioncall import ChatFunctionCall1, ChatFunctionCall1TypedDict
from typing import Union


CreateChatCompletionRequestBodyTypedDict = Union[ChatCompletionRequestTypedDict, ChatCompletionRequestJSONModeTypedDict, ChatFunctionCall1TypedDict]


CreateChatCompletionRequestBody = Union[ChatCompletionRequest, ChatCompletionRequestJSONMode, ChatFunctionCall1]


CreateChatCompletionResponseBodyTypedDict = Union[ChatCompletionResponseTypedDict, ChatCompletionResponseFunctionCallTypedDict, ChatCompletionResponseJSONModeTypedDict]
r"""OK"""


CreateChatCompletionResponseBody = Union[ChatCompletionResponse, ChatCompletionResponseFunctionCall, ChatCompletionResponseJSONMode]
r"""OK"""

