"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
from typing import TypedDict


class FileSchemaTypedDict(TypedDict):
    id: str
    r"""The file identifier, which can be referenced in the API endpoints"""
    object: str
    r"""The object type, which is always `file`."""
    bytes: int
    r"""The size of the file, in bytes."""
    created_at: int
    r"""The UNIX timestamp (in seconds) for when the file was created."""
    filename: str
    r"""The name of the file"""
    purpose: str
    r"""The intended purpose of the file. Only supports `fine-tune` for now."""
    

class FileSchema(BaseModel):
    id: str
    r"""The file identifier, which can be referenced in the API endpoints"""
    object: str
    r"""The object type, which is always `file`."""
    bytes: int
    r"""The size of the file, in bytes."""
    created_at: int
    r"""The UNIX timestamp (in seconds) for when the file was created."""
    filename: str
    r"""The name of the file"""
    purpose: str
    r"""The intended purpose of the file. Only supports `fine-tune` for now."""
    
