"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FineTuneableModel(str, Enum):
    r"""The name of the model to fine-tune."""
    OPEN_BEEZY_7B = "open-beezy-7b"
    BEEZY_SMALL_LATEST = "beezy-small-latest"

