"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .jobout import JobOut, JobOutTypedDict
from beezy_ai.types import BaseModel
import pydantic
from typing import Final, List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class JobsOutTypedDict(TypedDict):
    data: NotRequired[List[JobOutTypedDict]]
    

class JobsOut(BaseModel):
    data: Optional[List[JobOut]] = None
    OBJECT: Annotated[Final[Optional[str]], pydantic.Field(alias="object")] = "list"
    
