"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .fileschema import FileSchema, FileSchemaTypedDict
from beezy_ai.types import BaseModel
from typing import List, TypedDict


class ListFilesOutTypedDict(TypedDict):
    data: List[FileSchemaTypedDict]
    object: str
    

class ListFilesOut(BaseModel):
    data: List[FileSchema]
    object: str
    
