"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class MetricOutTypedDict(TypedDict):
    r"""Metrics at the step number during the fine-tuning job. Use these metrics to
    assess if the training is going smoothly (loss should decrease, token accuracy
    should increase).

    """
    
    train_loss: NotRequired[float]
    valid_loss: NotRequired[float]
    valid_mean_token_accuracy: NotRequired[float]
    

class MetricOut(BaseModel):
    r"""Metrics at the step number during the fine-tuning job. Use these metrics to
    assess if the training is going smoothly (loss should decrease, token accuracy
    should increase).

    """
    
    train_loss: Optional[float] = None
    valid_loss: Optional[float] = None
    valid_mean_token_accuracy: Optional[float] = None
    
