"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .model import Model, ModelTypedDict
from beezy_ai.types import BaseModel
from typing import List, TypedDict


class ModelListTypedDict(TypedDict):
    object: str
    data: List[ModelTypedDict]
    

class ModelList(BaseModel):
    object: str
    data: List[Model]
    
