"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
import pydantic
from typing import Final, TypedDict
from typing_extensions import Annotated


class RetrieveFileOutTypedDict(TypedDict):
    id: str
    object: str
    bytes: int
    created_at: int
    filename: str
    

class RetrieveFileOut(BaseModel):
    id: str
    object: str
    bytes: int
    created_at: int
    filename: str
    PURPOSE: Annotated[Final[str], pydantic.Field(alias="purpose")] = "fine-tune"
    
