"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionstreamrequest import ChatCompletionStreamRequest, ChatCompletionStreamRequestTypedDict
from .chatfunctioncall import ChatFunctionCall, ChatFunctionCallTypedDict
from .jsonmode import JSONMode, JSONModeTypedDict
from typing import Union


StreamChatCompletionsRequestBodyTypedDict = Union[ChatCompletionStreamRequestTypedDict, JSONModeTypedDict, ChatFunctionCallTypedDict]


StreamChatCompletionsRequestBody = Union[ChatCompletionStreamRequest, JSONMode, ChatFunctionCall]

