"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
import beezy_ai.utils as utils
from typing import Any, Optional

class TooManyRequestsData(BaseModel):
    description: Any
    extras: Any
    key: Optional[str] = None
    


class TooManyRequests(Exception):
    r"""Rate Limit Exceeded"""
    data: TooManyRequestsData

    def __init__(self, data: TooManyRequestsData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, TooManyRequestsData)

