"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
import beezy_ai.utils as utils
from typing import Any, Optional

class UnauthorizedData(BaseModel):
    extras: Any
    description: Optional[str] = "Unauthorized"
    key: Optional[str] = None
    


class Unauthorized(Exception):
    r"""Unauthorized"""
    data: UnauthorizedData

    def __init__(self, data: UnauthorizedData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, UnauthorizedData)

