"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UsageInfoTypedDict(TypedDict):
    prompt_tokens: int
    total_tokens: int
    completion_tokens: NotRequired[int]
    

class UsageInfo(BaseModel):
    prompt_tokens: int
    total_tokens: int
    completion_tokens: Optional[int] = None
    
