"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from beezy_ai.types import BaseModel
import pydantic
from typing import Final, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class WandbIntegrationOutTypedDict(TypedDict):
    project: str
    r"""The name of the project that the new run will be created under."""
    name: NotRequired[str]
    r"""A display name to set for the run. If not set, will use the job ID as the name."""
    run_name: NotRequired[str]
    

class WandbIntegrationOut(BaseModel):
    project: str
    r"""The name of the project that the new run will be created under."""
    TYPE: Annotated[Final[Optional[str]], pydantic.Field(alias="type")] = "wandb"
    name: Optional[str] = None
    r"""A display name to set for the run. If not set, will use the job ID as the name."""
    run_name: Optional[str] = None
    
